### ISSUE TITLE
望提供依据时间生成ID的接口.

### ISSUE THREAD

**Issue by km3945** [osgochina/donkeyid#1]
在实际运用中.老系统想要迁移到此ID方案时,需要一个依据数据原有时间生成ID的接口.

因为我在设计数据库时,利用新ID的特点,我会省一个数据创建时间字段.因为ID中可以取到．
所以在老系统迁移时就需要一个这样的接口.从时间来获得唯一ID.这样以迁移后,我就能从ID中获得该数据的生成时间.

**Comment by osgochina** [comment]
已经提供$donkeyid->getIdByTime($time,$num);
