### ISSUE TITLE
donkeyid是基于swoole

### ISSUE THREAD

**Issue by lik0914** [osgochina/donkeyid#11]
如题， donkeyid是基依赖swoole的吗？还是有swoole版本呢？

**Comment by osgochina** [comment]
Donkeyid是php扩展，不依赖于其他第三方库，但是donkeyid server 是依赖于swoole，donkeyid server能够通过http请求生成id，当然，你也可以通过自己封装server提供http接口。

**Comment by lik0914** [comment]
谢谢， 你的回答， donkeyid.so 相当于 donkeyid server的客户端去连接server生成ID
