### ISSUE TITLE
要是nodeid能作为参数传进去就好了

### ISSUE THREAD

**Issue by cesardeng** [osgochina/donkeyid#16]
现在一台机器上启动多个相同的进程，id会有重复。

**Comment by osgochina** [comment]
支持进程内设置nodeid
进程启动的时候,单独设置
ini_set('donkeyid.node_id',1);

**Comment by cesardeng** [comment]
不好意思，没有看仔细。大侠考虑的这么周全，👍

**Comment by cesardeng** [comment]
大侠。。。。你的最新发布1.0版本没有包涵这个特性。。。。
对比了最新代码才发现。。。。😭，现在已经ok

**Comment by osgochina** [comment]
用master版本吧.
