### ISSUE TITLE
dk_parse_id解析id时候遇到的问题,json_encode后键名带有\u0000无法获取到详细的值

### ISSUE THREAD

**Issue by shijunjun** [osgochina/donkeyid#18]
$data = dk_parse_id("6492052405004271616")
json_encode后是这样的:{"time\u0000":"1547825909854","node_id\u0000":0,"sequence\u0000":0}
导致$data['time'] 获取不到值

我想请教下这种问题我该如何解决,谢谢!

**Comment by shijunjun** [comment]
已经解决了,修改了一下donkeyid/donkeyid/donkeyid.c文件中的 331 332 333 359 360 361行的变量长度值,重新编译安装了一下

**Comment by osgochina** [comment]
你可以提个pr吗?我合并到主分支

**Comment by shijunjun** [comment]
不好意思刚看到你的回复，这几天回老家了事比较多在一个回来的时候也没带电脑，等我过两天回去了我在提pr吧
