### ISSUE TITLE
本机节点不应从脚本设置.可放到PHP.INI中

### ISSUE THREAD

**Issue by km3945** [osgochina/donkeyid#2]
本机节点不应从脚本设置.可放到PHP.INI中
当然.接口是可以留的..用户自己设置就用设置的.否则从PHP.INI中获取.

**Comment by km3945** [comment]
实际运用中.多服务器,不可能为这个节点ID去写不同的配置文件

**Comment by osgochina** [comment]
搞定，支持从php.ini中配置nodeid.支持php7
