### ISSUE TITLE
不支持php8

### ISSUE THREAD

**Issue by smashdog** [osgochina/donkeyid#21]
在make时出错
`
[root@DESKTOP-RN8D2NJ donkeyid]# make
/bin/sh /root/donkeyid/libtool --mode=compile cc -I. -I/root/donkeyid -I/root/donkeyid/include -I/root/donkeyid/main -I/root/donkeyid -I/opt/remi/php80/root/usr/include/php -I/opt/remi/php80/root/usr/include/php/main -I/opt/remi/php80/root/usr/include/php/TSRM -I/opt/remi/php80/root/usr/include/php/Zend -I/opt/remi/php80/root/usr/include/php/ext -I/opt/remi/php80/root/usr/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2    -c /root/donkeyid/donkeyid.c -o donkeyid.lo
libtool: compile:  cc -I. -I/root/donkeyid -I/root/donkeyid/include -I/root/donkeyid/main -I/root/donkeyid -I/opt/remi/php80/root/usr/include/php -I/opt/remi/php80/root/usr/include/php/main -I/opt/remi/php80/root/usr/include/php/TSRM -I/opt/remi/php80/root/usr/include/php/Zend -I/opt/remi/php80/root/usr/include/php/ext -I/opt/remi/php80/root/usr/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /root/donkeyid/donkeyid.c  -fPIC -DPIC -o .libs/donkeyid.o
In file included from /root/donkeyid/donkeyid.c:29:
/root/donkeyid/php_wrapper.h: In function ‘dk_zend_read_property’:
/root/donkeyid/php_wrapper.h:28:37: warning: passing argument 2 of ‘zend_read_property’ from incompatible pointer type
-Wincompatible-pointer-types]
     return zend_read_property(scope,object,name,name_length,silent,&rv);
                                     ^~~~~~
In file included from /opt/remi/php80/root/usr/include/php/main/php.h:35,
                 from /root/donkeyid/donkeyid.c:25:
/opt/remi/php80/root/usr/include/php/Zend/zend_API.h:404:16: note: expected ‘zend_object *’ {aka ‘struct _zend_object *’} but argument is of type ‘zval *’ {aka ‘struct _zval_struct *’}
 ZEND_API zval *zend_read_property(zend_class_entry *scope, zend_object *object, const char *name, size_t name_length, zend_bool silent, zval *rv);
                ^~~~~~~~~~~~~~~~~~
/root/donkeyid/donkeyid.c: In function ‘zif_dk_get_next_ids’:
/root/donkeyid/donkeyid.c:233:46: error: expected ‘)’ before ‘TSRMLS_CC’
     if (zend_parse_parameters(ZEND_NUM_ARGS()TSRMLS_CC, "l|s",&num, &val, &val_len) == FAILURE) {
                                              ^~~~~~~~~
/root/donkeyid/donkeyid.c:233:9: error: too few arguments to function ‘zend_parse_parameters’
     if (zend_parse_parameters(ZEND_NUM_ARGS()TSRMLS_CC, "l|s",&num, &val, &val_len) == FAILURE) {
         ^~~~~~~~~~~~~~~~~~~~~
In file included from /opt/remi/php80/root/usr/include/php/main/php.h:35,
                 from /root/donkeyid/donkeyid.c:25:
/opt/remi/php80/root/usr/include/php/Zend/zend_API.h:304:22: note: declared here
 ZEND_API zend_result zend_parse_parameters(uint32_t num_args, const char *type_spec, ...);
                      ^~~~~~~~~~~~~~~~~~~~~
/root/donkeyid/donkeyid.c: In function ‘zif_dk_get_ts_ids’:
/root/donkeyid/donkeyid.c:275:46: error: expected ‘)’ before ‘TSRMLS_CC’
     if (zend_parse_parameters(ZEND_NUM_ARGS()TSRMLS_CC, "l|s",&num, &val, &val_len) == FAILURE) {
                                              ^~~~~~~~~
/root/donkeyid/donkeyid.c:275:9: error: too few arguments to function ‘zend_parse_parameters’
     if (zend_parse_parameters(ZEND_NUM_ARGS()TSRMLS_CC, "l|s",&num, &val, &val_len) == FAILURE) {
         ^~~~~~~~~~~~~~~~~~~~~
In file included from /opt/remi/php80/root/usr/include/php/main/php.h:35,
                 from /root/donkeyid/donkeyid.c:25:
/opt/remi/php80/root/usr/include/php/Zend/zend_API.h:304:22: note: declared here
 ZEND_API zend_result zend_parse_parameters(uint32_t num_args, const char *type_spec, ...);
                      ^~~~~~~~~~~~~~~~~~~~~
/root/donkeyid/donkeyid.c: In function ‘zif_dk_parse_ts_id’:
/root/donkeyid/donkeyid.c:315:46: error: expected ‘)’ before ‘TSRMLS_CC’
     if (zend_parse_parameters(ZEND_NUM_ARGS()TSRMLS_CC, "s", &val, &val_len) == FAILURE) {
                                              ^~~~~~~~~
/root/donkeyid/donkeyid.c:315:9: error: too few arguments to function ‘zend_parse_parameters’
     if (zend_parse_parameters(ZEND_NUM_ARGS()TSRMLS_CC, "s", &val, &val_len) == FAILURE) {
         ^~~~~~~~~~~~~~~~~~~~~
In file included from /opt/remi/php80/root/usr/include/php/main/php.h:35,
                 from /root/donkeyid/donkeyid.c:25:
/opt/remi/php80/root/usr/include/php/Zend/zend_API.h:304:22: note: declared here
 ZEND_API zend_result zend_parse_parameters(uint32_t num_args, const char *type_spec, ...);
                      ^~~~~~~~~~~~~~~~~~~~~
/root/donkeyid/donkeyid.c: In function ‘zif_dk_parse_id’:
/root/donkeyid/donkeyid.c:343:46: error: expected ‘)’ before ‘TSRMLS_CC’
     if (zend_parse_parameters(ZEND_NUM_ARGS()TSRMLS_CC, "s", &val, &val_len) == FAILURE) {
                                              ^~~~~~~~~
/root/donkeyid/donkeyid.c:343:9: error: too few arguments to function ‘zend_parse_parameters’
     if (zend_parse_parameters(ZEND_NUM_ARGS()TSRMLS_CC, "s", &val, &val_len) == FAILURE) {
         ^~~~~~~~~~~~~~~~~~~~~
In file included from /opt/remi/php80/root/usr/include/php/main/php.h:35,
                 from /root/donkeyid/donkeyid.c:25:
/opt/remi/php80/root/usr/include/php/Zend/zend_API.h:304:22: note: declared here
 ZEND_API zend_result zend_parse_parameters(uint32_t num_args, const char *type_spec, ...);
                      ^~~~~~~~~~~~~~~~~~~~~
make: *** [Makefile:208: donkeyid.lo] Error 1
`

**Comment by osgochina** [comment]
已支持php8
