### ISSUE TITLE
Mac OS下编译报错

### ISSUE THREAD

**Issue by LinkedDestiny** [osgochina/donkeyid#4]
头文件malloc.h在MacOS的路径为sys/malloc.h，建议加上对系统的判定

**Comment by osgochina** [comment]
手头没有mac，你可以提交代码，我合并进主线

**Comment by deliangyang** [comment]
Linux debian 3.2.0-4-amd64 #1 SMP Debian 3.2.81-1 x86_64 GNU/Linux
编译出现Segmentation fault

**Comment by liumingzhij26** [comment]
我之前也在想写一个这样的扩展，没想到已经有人写了，太帅了，我现在还在使用uuid_short()
