### ISSUE TITLE
php7下报错

### ISSUE THREAD

**Issue by cloudk** [osgochina/donkeyid#8]
php版本 PHP 7.0.9 
php -v
[1]    49550 segmentation fault  php -v

**Comment by osgochina** [comment]
能把执行的代码给我看看吗？是安装了直接报错还是执行那个代码的时候报错？

**Comment by cloudk** [comment]
安装后 命令行下执行 php -v 就报错了.

**Comment by osgochina** [comment]
请问下你是什么操作系统，内核版本是什么？我好重现这个问题

**Comment by cloudk** [comment]
centos7.2和mac都出现这个问题
