### ISSUE TITLE
1.0版本稳定了吗

### ISSUE THREAD

**Issue by soooldier** [osgochina/donkeyid#9]
嗨，您好。现在需要一个高性能的id生成器，碰巧看到了你的donkeyid。但是我在release里没有看到1.0版本，请问1.0版本稳定了吗？

**Comment by osgochina** [comment]
目前最新版本已经稳定，线上使用超过5个月，没有任何问题，只是没有发布1.0版本而已

**Comment by soooldier** [comment]
@osgochina 感谢作者 🙏
